replicaCount: 2

env:
  - name: SPRING_PROFILES_ACTIVE
    value: uat

podAnnotations:
  environment: uat

ingress:
  hosts:
    - host: app-uat.mergeai.in
      paths:
        - path: /
          pathType: Prefix
