replicaCount: 2

env:
  - name: SPRING_PROFILES_ACTIVE
    value: staging

podAnnotations:
  environment: staging

ingress:
  hosts:
    - host: app-staging.mergeai.in
      paths:
        - path: /
          pathType: Prefix
